# rng_seed: 1234
n_sweep:
  start: 10
  dvstart: 5
  ddvstart: 3

mushrooms:
  rho_lb: 1.1
  rho_ub: 2.0
  increment: 0.1

lung-cancer:
  # rho:
  rho_lb: 0.1
  rho_ub: 1.0
  increment: 0.1
  # rho_lb:

similarity:
  - single
  - average
  - complete
  - median
